//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaniDBEntities : DbContext
    {
        public SaniDBEntities()
            : base("name=SaniDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAssignToOff> tblAssignToOff { get; set; }
        public virtual DbSet<tblBlog> tblBlog { get; set; }
        public virtual DbSet<tblBlogCategory> tblBlogCategory { get; set; }
        public virtual DbSet<tblBranch> tblBranch { get; set; }
        public virtual DbSet<tblBranchService> tblBranchService { get; set; }
        public virtual DbSet<tblContactUs> tblContactUs { get; set; }
        public virtual DbSet<tblCustomerAddress> tblCustomerAddress { get; set; }
        public virtual DbSet<tblDocuments> tblDocuments { get; set; }
        public virtual DbSet<tblElctricShop> tblElctricShop { get; set; }
        public virtual DbSet<tblElectricShopCustomers> tblElectricShopCustomers { get; set; }
        public virtual DbSet<tblFaq> tblFaq { get; set; }
        public virtual DbSet<tblForceCancels> tblForceCancels { get; set; }
        public virtual DbSet<tblForcePreRegister> tblForcePreRegister { get; set; }
        public virtual DbSet<tblForceRating> tblForceRating { get; set; }
        public virtual DbSet<tblOff> tblOff { get; set; }
        public virtual DbSet<tblPage> tblPage { get; set; }
        public virtual DbSet<tblPaymentLogs> tblPaymentLogs { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblService> tblService { get; set; }
        public virtual DbSet<tblServiceCategory> tblServiceCategory { get; set; }
        public virtual DbSet<tblState_City> tblState_City { get; set; }
        public virtual DbSet<tblSystemVariabels> tblSystemVariabels { get; set; }
        public virtual DbSet<tblForce> tblForce { get; set; }
        public virtual DbSet<tblForceExpertise> tblForceExpertise { get; set; }
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
        public virtual DbSet<tblFactor> tblFactor { get; set; }
        public virtual DbSet<tblAssignToFactor> tblAssignToFactor { get; set; }
        public virtual DbSet<tblOprator> tblOprator { get; set; }
    }
}
