//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignToFactor
    {
        public int id { get; set; }
        public System.Guid factorId { get; set; }
        public System.Guid serviceId { get; set; }
        public int count { get; set; }
    
        public virtual tblFactor tblFactor { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
