//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranchService
    {
        public System.Guid bCode { get; set; }
        public System.Guid serviceId { get; set; }
        public long price { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
