//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBranch()
        {
            this.tblAssignToOff = new HashSet<tblAssignToOff>();
            this.tblBranchService = new HashSet<tblBranchService>();
            this.tblDocuments = new HashSet<tblDocuments>();
            this.tblElctricShop = new HashSet<tblElctricShop>();
            this.tblForce = new HashSet<tblForce>();
            this.tblFactor = new HashSet<tblFactor>();
            this.tblOprator = new HashSet<tblOprator>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string branchTel { get; set; }
        public string managerName { get; set; }
        public string managerTel { get; set; }
        public string managerPhoneNumber { get; set; }
        public string managerNationalCode { get; set; }
        public int locationId { get; set; }
        public string address { get; set; }
        public double lat { get; set; }
        public double lng { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignToOff> tblAssignToOff { get; set; }
        public virtual tblState_City tblState_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBranchService> tblBranchService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocuments> tblDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblElctricShop> tblElctricShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForce> tblForce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactor> tblFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOprator> tblOprator { get; set; }
    }
}
