//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblAssignToOff = new HashSet<tblAssignToOff>();
            this.tblCustomerAddress = new HashSet<tblCustomerAddress>();
            this.tblElectricShopCustomers = new HashSet<tblElectricShopCustomers>();
            this.tblForceRating = new HashSet<tblForceRating>();
            this.tblPaymentLogs = new HashSet<tblPaymentLogs>();
            this.tblFactor = new HashSet<tblFactor>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public int locationId { get; set; }
        public string pIntroduceCode { get; set; }
        public string mIntroduceCode { get; set; }
        public long credit { get; set; }
        public long creditor { get; set; }
        public string pusheId { get; set; }
        public bool status { get; set; }
        public string token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignToOff> tblAssignToOff { get; set; }
        public virtual tblState_City tblState_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerAddress> tblCustomerAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblElectricShopCustomers> tblElectricShopCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForceRating> tblForceRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentLogs> tblPaymentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactor> tblFactor { get; set; }
    }
}
