//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerAddress()
        {
            this.tblFactor = new HashSet<tblFactor>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid customerId { get; set; }
        public int locationId { get; set; }
        public string address { get; set; }
        public double lat { get; set; }
        public double lng { get; set; }
    
        public virtual tblState_City tblState_City { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactor> tblFactor { get; set; }
    }
}
