//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactUs
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string PhoneNumber { get; set; }
        public string message { get; set; }
        public string ip { get; set; }
        public string sendDate { get; set; }
        public Nullable<bool> isRead { get; set; }
    }
}
