//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocuments
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> bCode { get; set; }
        public Nullable<System.Guid> elctricShopId { get; set; }
        public Nullable<System.Guid> forceId { get; set; }
        public string title { get; set; }
        public string path { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblElctricShop tblElctricShop { get; set; }
        public virtual tblForce tblForce { get; set; }
    }
}
