//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElctricShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblElctricShop()
        {
            this.tblAssignToOff = new HashSet<tblAssignToOff>();
            this.tblDocuments = new HashSet<tblDocuments>();
            this.tblElectricShopCustomers = new HashSet<tblElectricShopCustomers>();
            this.tblPaymentLogs = new HashSet<tblPaymentLogs>();
            this.tblFactor = new HashSet<tblFactor>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public string pass { get; set; }
        public string title { get; set; }
        public string shopTel { get; set; }
        public string managerName { get; set; }
        public string managerTel { get; set; }
        public string managerPhoneNumber { get; set; }
        public string managerNationalCode { get; set; }
        public System.Guid bCode { get; set; }
        public System.DateTime dateRegister { get; set; }
        public string address { get; set; }
        public long creditor { get; set; }
        public byte benefitPercent { get; set; }
        public string shabaNumber { get; set; }
        public string pusheId { get; set; }
        public bool status { get; set; }
        public string token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignToOff> tblAssignToOff { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocuments> tblDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblElectricShopCustomers> tblElectricShopCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentLogs> tblPaymentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactor> tblFactor { get; set; }
    }
}
