//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElectricShopCustomers
    {
        public System.Guid eShopId { get; set; }
        public System.Guid customerId { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual tblElctricShop tblElctricShop { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
