//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForceRating
    {
        public System.Guid forceId { get; set; }
        public System.Guid customerId { get; set; }
        public System.Guid factorId { get; set; }
        public byte rate { get; set; }
        public string comment { get; set; }
    
        public virtual tblForce tblForce { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblFactor tblFactor { get; set; }
    }
}
