//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblForce()
        {
            this.tblDocuments = new HashSet<tblDocuments>();
            this.tblForceCancels = new HashSet<tblForceCancels>();
            this.tblForceRating = new HashSet<tblForceRating>();
            this.tblPaymentLogs = new HashSet<tblPaymentLogs>();
            this.tblForceExpertise = new HashSet<tblForceExpertise>();
            this.tblFactor = new HashSet<tblFactor>();
        }
    
        public System.Guid id { get; set; }
        public string image { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public string telNumber { get; set; }
        public string nationalCode { get; set; }
        public string personalCode { get; set; }
        public string pass { get; set; }
        public string address { get; set; }
        public double lat { get; set; }
        public double lng { get; set; }
        public System.Guid bCode { get; set; }
        public string mIntrodouceCode { get; set; }
        public System.DateTime dateRegister { get; set; }
        public long creditor { get; set; }
        public long debtor { get; set; }
        public byte benefitPercent { get; set; }
        public byte cancelRequestCount { get; set; }
        public string birthDate { get; set; }
        public byte rate { get; set; }
        public Nullable<System.TimeSpan> timeOfBlock { get; set; }
        public string shabaNumber { get; set; }
        public string pusheId { get; set; }
        public string token { get; set; }
        public byte status { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocuments> tblDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForceCancels> tblForceCancels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForceRating> tblForceRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentLogs> tblPaymentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForceExpertise> tblForceExpertise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactor> tblFactor { get; set; }
    }
}
