//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForceExpertise
    {
        public System.Guid forceId { get; set; }
        public System.Guid catId { get; set; }
        public byte cent { get; set; }
    
        public virtual tblForce tblForce { get; set; }
        public virtual tblServiceCategory tblServiceCategory { get; set; }
    }
}
