//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForcePreRegister
    {
        public decimal tellNumber { get; set; }
        public string name { get; set; }
        public int city { get; set; }
    
        public virtual tblState_City tblState_City { get; set; }
    }
}
