//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFactor()
        {
            this.tblForceCancels = new HashSet<tblForceCancels>();
            this.tblForceRating = new HashSet<tblForceRating>();
            this.tblAssignToFactor = new HashSet<tblAssignToFactor>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public System.Guid customerId { get; set; }
        public Nullable<System.Guid> forceId { get; set; }
        public Nullable<System.Guid> elctricShopId { get; set; }
        public Nullable<System.Guid> opratorId { get; set; }
        public System.Guid bCode { get; set; }
        public bool paymentType { get; set; }
        public bool paymentStatus { get; set; }
        public Nullable<byte> cancelReason { get; set; }
        public string suspendResaon { get; set; }
        public string confirmSignature { get; set; }
        public bool isPrint { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public Nullable<System.DateTime> forceStartDate { get; set; }
        public Nullable<System.DateTime> forceEndDate { get; set; }
        public Nullable<System.Guid> addressId { get; set; }
        public Nullable<System.Guid> offId { get; set; }
        public Nullable<long> offCount { get; set; }
        public long totalCount { get; set; }
        public byte status { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblCustomerAddress tblCustomerAddress { get; set; }
        public virtual tblElctricShop tblElctricShop { get; set; }
        public virtual tblOff tblOff { get; set; }
        public virtual tblForce tblForce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForceCancels> tblForceCancels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForceRating> tblForceRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignToFactor> tblAssignToFactor { get; set; }
        public virtual tblOprator tblOprator { get; set; }
    }
}
