//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOff()
        {
            this.tblFactor = new HashSet<tblFactor>();
        }
    
        public System.Guid id { get; set; }
        public string title { get; set; }
        public string code { get; set; }
        public byte offType { get; set; }
        public byte Indicator { get; set; }
        public string sIndicator { get; set; }
        public string eindicator { get; set; }
        public Nullable<long> minFalseExe { get; set; }
        public Nullable<long> maxFalseExe { get; set; }
        public Nullable<bool> offCountIndicator { get; set; }
        public Nullable<long> offCount { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactor> tblFactor { get; set; }
    }
}
