//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOprator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOprator()
        {
            this.tblFactor = new HashSet<tblFactor>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string pass { get; set; }
        public string phoneNumber { get; set; }
        public string telNumber { get; set; }
        public string nationalCode { get; set; }
        public string birthDate { get; set; }
        public string shabaNumber { get; set; }
        public Nullable<System.Guid> bCode { get; set; }
        public string address { get; set; }
        public int roleId { get; set; }
        public System.DateTime dateRegister { get; set; }
        public Nullable<byte> loginFailedCount { get; set; }
        public Nullable<System.DateTime> blockTime { get; set; }
        public bool status { get; set; }
        public string token { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFactor> tblFactor { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
