//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPage
    {
        public string url { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<int> visitCount { get; set; }
        public string seoTitle { get; set; }
        public string seoDescription { get; set; }
        public string seoTags { get; set; }
    }
}
