//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentLogs
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> electricShopId { get; set; }
        public Nullable<System.Guid> forceId { get; set; }
        public Nullable<System.Guid> customerId { get; set; }
        public string trackingCode { get; set; }
        public string description { get; set; }
        public long price { get; set; }
        public System.DateTime date { get; set; }
        public bool type { get; set; }
    
        public virtual tblElctricShop tblElctricShop { get; set; }
        public virtual tblForce tblForce { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
