//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemVariabels
    {
        public string cAppVersionCode { get; set; }
        public string fAppVersionCode { get; set; }
        public string eAppVersionCode { get; set; }
    }
}
