//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblService()
        {
            this.tblBranchService = new HashSet<tblBranchService>();
            this.tblAssignToFactor = new HashSet<tblAssignToFactor>();
        }
    
        public System.Guid id { get; set; }
        [Required(ErrorMessage ="asfsdfg")]
        public string title { get; set; }
        public bool unit { get; set; }
        public Nullable<System.Guid> catId { get; set; }
        public string description { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBranchService> tblBranchService { get; set; }
        public virtual tblServiceCategory tblServiceCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignToFactor> tblAssignToFactor { get; set; }
    }
}
